[profile.default]
src = 'src'
test = 'test/foundry'
libs = ['lib']
out = 'out'
cache_path  = 'forge-cache'
verbosity = 2
optimizer=true
optimizer_runs=1000

# For saving deployment addresses
# fs_permissions = [{ access = "read-write", path = "./deployments"}]

build_info=true
extra_output = ["storageLayout"]


# comment out if you notice any weird behavior
# sparse_mode = true
remappings = [
 "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
 "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
auto_detect_remappings = false

# do not use for computationally expensive tests
[profile.intense.fuzz]
runs = 10000

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
